version: "3.9"
services:

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./infra/keycloak/realm-export.json:/tmp/realm-export.json
    command:
      -Dkeycloak.profile.feature.upload_scripts=enabled
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - keycloak_db:/var/lib/postgresql/data

volumes:
  keycloak_db:
